version: '3.8'

services:
  nginx:
    image: rajalakshmi1404/custom-nginx:latest
    ports:
      - "80:80"  # Map port 80 on the host to port 80 in the container
      - "443:443" # Map port 443 on the host to port 443 in the container 
    volumes:
      - /var/opt/nginx:/usr/share/nginx/html:ro  # Bind mount the host directory to the container
    restart: always

